/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/AlertDialog.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarToast: typeof import('./src/components/SnackbarToast.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
  }
}
